# Model Optimizations

In this notebook, the goal is to take our base models saved under the /work/models/ section and further enhance their predictability by fine-tuning their hyperparameters.

## Importing our data

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, recall_score, precision_score, f1_score
from math import sqrt
import os
import csv

# Load the trainset
train_file_path = '/work/Downloaded/vbd-richard-bernat/trainn.csv'
test_file_path = '/work/Downloaded/test.csv'
train = pd.read_csv(train_file_path)
test = pd.read_csv(test_file_path)

# Placeholder for trainset preprocessing
#target = 'your_target_column'
#features = train.drop(target, axis=1)

from sklearn.preprocessing import LabelEncoder

# Encoding the target variable
label_encoder = LabelEncoder()
train['prognosis_encoded'] = label_encoder.fit_transform(train['prognosis'])

# Separating features and target variable
#X = train.drop(['id', 'prognosis', 'prognosis_encoded'], axis=1)
X = train.drop(['prognosis', 'prognosis_encoded'], axis=1)

y = train['prognosis_encoded']



# Split the trainset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=29)

#Importing our base models

In [ ]:
import joblib  
from tensorflow.keras.models import load_model

ann =load_model('/work/models/ann.keras')
dt = joblib.load('/work/models/decision_tree.joblib')
rf = joblib.load('/work/models/random_forest.joblib')
xg_boost = joblib.load('/work/models/decision_tree.joblib')
knn = joblib.load('/work/models/decision_tree.joblib')


knn.fit(X_test,y_test)

2024-05-16 09:27:56.415136: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-05-16 09:27:56.415171: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2024-05-16 09:27:56.415192: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (p-82fc1969-7ff0-4344-a3e7-65ed95a291e5): /proc/driver/nvidia/version does not exist
2024-05-16 09:27:56.415439: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

DecisionTreeClassifier(max_depth=20)

## Hyperparameter tuning - ANN

In [0]:
import numpy as np
from tensorflow.keras.models import Sequential, save_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


# Define a function to create your model
def create_model(hidden_units=128, activation='relu', optimizer='adam'):
    model = Sequential([
        Dense(hidden_units, input_shape=(X_train.shape[1],), activation=activation),
        Dense(64, activation=activation),
        Dense(len(np.unique(y)), activation='softmax')  # Ensure output layer matches the number of classes
    ])
    model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# Create KerasClassifier based on your model function
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=1)

# Define the grid search parameters
param_grid = {
    'hidden_units': [8, 16, 32,64,128],
    'activation': ['relu', 'tanh'],
    'optimizer': ['adam', 'rmsprop']
}

# Perform GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='accuracy')
grid_result = grid.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_result.best_params_

# Create a new model with the best hyperparameters
best_model = create_model(**best_params)

# Train the best model on the entire training dataset
best_model.fit(X_train, y_train, epochs=10, batch_size=10, verbose=1)

# Save the best model
save_model(best_model, '/work/models/best_ann_model.h5')

# Evaluate the best model on the test data
loss, accuracy = best_model.evaluate(X_test, y_test, verbose=0)
print("Test Accuracy:", accuracy)

Epoch 14/100
12/12 [==============================] - 0s 1ms/step - loss: 0.1484 - accuracy: 1.0000
Epoch 15/100
12/12 [==============================] - 0s 7ms/step - loss: 0.1277 - accuracy: 1.0000
Epoch 16/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1111 - accuracy: 1.0000
Epoch 17/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0982 - accuracy: 1.0000
Epoch 18/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0882 - accuracy: 1.0000
Epoch 19/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0786 - accuracy: 1.0000
Epoch 20/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0716 - accuracy: 1.0000
Epoch 21/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0645 - accuracy: 1.0000
Epoch 22/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0586 - accuracy: 1.0000
Epoch 23/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0538 - accuracy: 1.0000
Epoch 24/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0489 - accuracy: 1.0000
Epoch 25/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0454 - accuracy: 1.0000
Epoch 26/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0419 - accuracy: 1.0000
Epoch 27/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0386 - accuracy: 1.0000
Epoch 28/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0362 - accuracy: 1.0000
Epoch 29/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0340 - accuracy: 1.0000
Epoch 30/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0313 - accuracy: 1.0000
Epoch 31/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0294 - accuracy: 1.0000
Epoch 32/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0278 - accuracy: 1.0000
Epoch 33/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0262 - accuracy: 1.0000
Epoch 34/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0245 - accuracy: 1.0000
Epoch 35/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0232 - accuracy: 1.0000
Epoch 36/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0219 - accuracy: 1.0000
Epoch 37/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0208 - accuracy: 1.0000
Epoch 38/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0198 - accuracy: 1.0000
Epoch 39/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0188 - accuracy: 1.0000
Epoch 40/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0179 - accuracy: 1.0000
Epoch 41/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0171 - accuracy: 1.0000
Epoch 42/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0163 - accuracy: 1.0000
Epoch 43/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0156 - accuracy: 1.0000
Epoch 44/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0149 - accuracy: 1.0000
Epoch 45/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0143 - accuracy: 1.0000
Epoch 46/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0137 - accuracy: 1.0000
Epoch 47/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0132 - accuracy: 1.0000
Epoch 48/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0126 - accuracy: 1.0000
Epoch 49/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0121 - accuracy: 1.0000
Epoch 50/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0117 - accuracy: 1.0000
Epoch 51/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0113 - accuracy: 1.0000
Epoch 52/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0109 - accuracy: 1.0000
Epoch 53/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0105 - accuracy: 1.0000
Epoch 54/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0101 - accuracy: 1.0000
Epoch 55/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0098 - accuracy: 1.0000
Epoch 56/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0094 - accuracy: 1.0000
Epoch 57/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0091 - accuracy: 1.0000
Epoch 58/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0088 - accuracy: 1.0000
Epoch 59/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0085 - accuracy: 1.0000
Epoch 60/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0083 - accuracy: 1.0000
Epoch 61/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0080 - accuracy: 1.0000
Epoch 62/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 63/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0076 - accuracy: 1.0000
Epoch 64/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0073 - accuracy: 1.0000
Epoch 65/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0071 - accuracy: 1.0000
Epoch 66/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0069 - accuracy: 1.0000
Epoch 67/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0067 - accuracy: 1.0000
Epoch 68/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0065 - accuracy: 1.0000
Epoch 69/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 70/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0062 - accuracy: 1.0000
Epoch 71/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0060 - accuracy: 1.0000
Epoch 72/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0059 - accuracy: 1.0000
Epoch 73/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0057 - accuracy: 1.0000
Epoch 74/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0056 - accuracy: 1.0000
Epoch 75/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0054 - accuracy: 1.0000
Epoch 76/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0053 - accuracy: 1.0000
Epoch 77/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0052 - accuracy: 1.0000
Epoch 78/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0050 - accuracy: 1.0000
Epoch 79/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 80/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 81/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0047 - accuracy: 1.0000
Epoch 82/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 83/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0045 - accuracy: 1.0000
Epoch 84/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 85/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 86/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 87/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0041 - accuracy: 1.0000
Epoch 88/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 89/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0039 - accuracy: 1.0000
Epoch 90/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 91/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 92/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 93/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 94/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 95/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 96/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 97/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 98/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 99/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 100/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0031 - accuracy: 1.0000
2/2 [==============================] - 0s 2ms/step
Epoch 1/100
12/12 [==============================] - 0s 3ms/step - loss: 2.2817 - accuracy: 0.2564
Epoch 2/100
12/12 [==============================] - 0s 1ms/step - loss: 1.6456 - accuracy: 0.6581
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 1.2658 - accuracy: 0.8205
Epoch 4/100
12/12 [==============================] - 0s 1ms/step - loss: 0.9741 - accuracy: 0.9231
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 0.7470 - accuracy: 0.9402
Epoch 6/100
12/12 [==============================] - 0s 7ms/step - loss: 0.5723 - accuracy: 0.9658
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4291 - accuracy: 0.9829
Epoch 8/100
12/12 [==============================] - 0s 6ms/step - loss: 0.3277 - accuracy: 0.9829
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 0.2524 - accuracy: 0.9915
Epoch 10/100
12/12 [==============================] - 0s 1ms/step - loss: 0.1879 - accuracy: 0.9915
Epoch 11/100
12/12 [==============================] - 0s 1ms/step - loss: 0.1400 - accuracy: 1.0000
Epoch 12/100
12/12 [==============================] - 0s 1ms/step - loss: 0.1038 - accuracy: 1.0000
Epoch 13/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0755 - accuracy: 1.0000
Epoch 14/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0601 - accuracy: 1.0000
Epoch 15/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0425 - accuracy: 1.0000
Epoch 16/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0324 - accuracy: 1.0000
Epoch 17/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0255 - accuracy: 1.0000
Epoch 18/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0180 - accuracy: 1.0000
Epoch 19/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0136 - accuracy: 1.0000
Epoch 20/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0111 - accuracy: 1.0000
Epoch 21/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0076 - accuracy: 1.0000
Epoch 22/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0056 - accuracy: 1.0000
Epoch 23/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 24/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 25/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0024 - accuracy: 1.0000
Epoch 26/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0018 - accuracy: 1.0000
Epoch 27/100
12/12 [==============================] - 0s 1ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 28/100
12/12 [==============================] - 0s 6ms/step - loss: 9.2805e-04 - accuracy: 1.0000
Epoch 29/100
12/12 [==============================] - 0s 1ms/step - loss: 7.1371e-04 - accuracy: 1.0000
Epoch 30/100
12/12 [==============================] - 0s 1ms/step - loss: 5.5274e-04 - accuracy: 1.0000
Epoch 31/100
12/12 [==============================] - 0s 6ms/step - loss: 3.8321e-04 - accuracy: 1.0000
Epoch 32/100
12/12 [==============================] - 0s 2ms/step - loss: 2.7933e-04 - accuracy: 1.0000
Epoch 33/100
12/12 [==============================] - 0s 5ms/step - loss: 2.0337e-04 - accuracy: 1.0000
Epoch 34/100
12/12 [==============================] - 0s 1ms/step - loss: 1.5276e-04 - accuracy: 1.0000
Epoch 35/100
12/12 [==============================] - 0s 1ms/step - loss: 1.1021e-04 - accuracy: 1.0000
Epoch 36/100
12/12 [==============================] - 0s 6ms/step - loss: 7.6060e-05 - accuracy: 1.0000
Epoch 37/100
12/12 [==============================] - 0s 1ms/step - loss: 5.8724e-05 - accuracy: 1.0000
Epoch 38/100
12/12 [==============================] - 0s 1ms/step - loss: 4.2894e-05 - accuracy: 1.0000
Epoch 39/100
12/12 [==============================] - 0s 6ms/step - loss: 2.9966e-05 - accuracy: 1.0000
Epoch 40/100
12/12 [==============================] - 0s 1ms/step - loss: 2.1829e-05 - accuracy: 1.0000
Epoch 41/100
12/12 [==============================] - 0s 6ms/step - loss: 1.6456e-05 - accuracy: 1.0000
Epoch 42/100
12/12 [==============================] - 0s 1ms/step - loss: 1.1678e-05 - accuracy: 1.0000
Epoch 43/100
12/12 [==============================] - 0s 1ms/step - loss: 8.6788e-06 - accuracy: 1.0000
Epoch 44/100
12/12 [==============================] - 0s 6ms/step - loss: 6.2753e-06 - accuracy: 1.0000
Epoch 45/100
12/12 [==============================] - 0s 1ms/step - loss: 4.6400e-06 - accuracy: 1.0000
Epoch 46/100
12/12 [==============================] - 0s 1ms/step - loss: 3.5712e-06 - accuracy: 1.0000
Epoch 47/100
12/12 [==============================] - 0s 6ms/step - loss: 2.6735e-06 - accuracy: 1.0000
Epoch 48/100
12/12 [==============================] - 0s 1ms/step - loss: 2.0693e-06 - accuracy: 1.0000
Epoch 49/100
12/12 [==============================] - 0s 6ms/step - loss: 1.5844e-06 - accuracy: 1.0000
Epoch 50/100
12/12 [==============================] - 0s 1ms/step - loss: 1.2746e-06 - accuracy: 1.0000
Epoch 51/100
12/12 [==============================] - 0s 1ms/step - loss: 9.9952e-07 - accuracy: 1.0000
Epoch 52/100
12/12 [==============================] - 0s 1ms/step - loss: 8.1612e-07 - accuracy: 1.0000
Epoch 53/100
12/12 [==============================] - 0s 1ms/step - loss: 6.6024e-07 - accuracy: 1.0000
Epoch 54/100
12/12 [==============================] - 0s 6ms/step - loss: 5.6548e-07 - accuracy: 1.0000
Epoch 55/100
12/12 [==============================] - 0s 1ms/step - loss: 4.8397e-07 - accuracy: 1.0000
Epoch 56/100
12/12 [==============================] - 0s 1ms/step - loss: 4.2080e-07 - accuracy: 1.0000
Epoch 57/100
12/12 [==============================] - 0s 6ms/step - loss: 3.5763e-07 - accuracy: 1.0000
Epoch 58/100
12/12 [==============================] - 0s 1ms/step - loss: 3.1687e-07 - accuracy: 1.0000
Epoch 59/100
12/12 [==============================] - 0s 2ms/step - loss: 2.8121e-07 - accuracy: 1.0000
Epoch 60/100
12/12 [==============================] - 0s 1ms/step - loss: 2.4759e-07 - accuracy: 1.0000
Epoch 61/100
12/12 [==============================] - 0s 1ms/step - loss: 2.2110e-07 - accuracy: 1.0000
Epoch 62/100
12/12 [==============================] - 0s 6ms/step - loss: 1.9868e-07 - accuracy: 1.0000
Epoch 63/100
12/12 [==============================] - 0s 1ms/step - loss: 1.8034e-07 - accuracy: 1.0000
Epoch 64/100
12/12 [==============================] - 0s 2ms/step - loss: 1.6913e-07 - accuracy: 1.0000
Epoch 65/100
12/12 [==============================] - 0s 1ms/step - loss: 1.5487e-07 - accuracy: 1.0000
Epoch 66/100
12/12 [==============================] - 0s 1ms/step - loss: 1.3755e-07 - accuracy: 1.0000
Epoch 67/100
12/12 [==============================] - 0s 6ms/step - loss: 1.3245e-07 - accuracy: 1.0000
Epoch 68/100
12/12 [==============================] - 0s 1ms/step - loss: 1.2532e-07 - accuracy: 1.0000
Epoch 69/100
12/12 [==============================] - 0s 1ms/step - loss: 1.1513e-07 - accuracy: 1.0000
Epoch 70/100
12/12 [==============================] - 0s 6ms/step - loss: 1.0494e-07 - accuracy: 1.0000
Epoch 71/100
12/12 [==============================] - 0s 1ms/step - loss: 9.8832e-08 - accuracy: 1.0000
Epoch 72/100
12/12 [==============================] - 0s 1ms/step - loss: 8.8643e-08 - accuracy: 1.0000
Epoch 73/100
12/12 [==============================] - 0s 7ms/step - loss: 8.4567e-08 - accuracy: 1.0000
Epoch 74/100
12/12 [==============================] - 0s 1ms/step - loss: 7.8454e-08 - accuracy: 1.0000
Epoch 75/100
12/12 [==============================] - 0s 6ms/step - loss: 7.5397e-08 - accuracy: 1.0000
Epoch 76/100
12/12 [==============================] - 0s 1ms/step - loss: 6.7246e-08 - accuracy: 1.0000
Epoch 77/100
12/12 [==============================] - 0s 1ms/step - loss: 6.4190e-08 - accuracy: 1.0000
Epoch 78/100
12/12 [==============================] - 0s 6ms/step - loss: 6.1133e-08 - accuracy: 1.0000
Epoch 79/100
12/12 [==============================] - 0s 1ms/step - loss: 5.8076e-08 - accuracy: 1.0000
Epoch 80/100
12/12 [==============================] - 0s 6ms/step - loss: 5.4001e-08 - accuracy: 1.0000
Epoch 81/100
12/12 [==============================] - 0s 1ms/step - loss: 5.0944e-08 - accuracy: 1.0000
Epoch 82/100
12/12 [==============================] - 0s 1ms/step - loss: 4.7887e-08 - accuracy: 1.0000
Epoch 83/100
12/12 [==============================] - 0s 6ms/step - loss: 4.5850e-08 - accuracy: 1.0000
Epoch 84/100
12/12 [==============================] - 0s 1ms/step - loss: 3.8718e-08 - accuracy: 1.0000
Epoch 85/100
12/12 [==============================] - 0s 6ms/step - loss: 3.5661e-08 - accuracy: 1.0000
Epoch 86/100
12/12 [==============================] - 0s 1ms/step - loss: 3.3623e-08 - accuracy: 1.0000
Epoch 87/100
12/12 [==============================] - 0s 1ms/step - loss: 3.1585e-08 - accuracy: 1.0000
Epoch 88/100
12/12 [==============================] - 0s 6ms/step - loss: 2.9548e-08 - accuracy: 1.0000
Epoch 89/100
12/12 [==============================] - 0s 1ms/step - loss: 2.7510e-08 - accuracy: 1.0000
Epoch 90/100
12/12 [==============================] - 0s 1ms/step - loss: 2.1397e-08 - accuracy: 1.0000
Epoch 91/100
12/12 [==============================] - 0s 6ms/step - loss: 2.2415e-08 - accuracy: 1.0000
Epoch 92/100
12/12 [==============================] - 0s 1ms/step - loss: 1.9359e-08 - accuracy: 1.0000
Epoch 93/100
12/12 [==============================] - 0s 6ms/step - loss: 2.0378e-08 - accuracy: 1.0000
Epoch 94/100
12/12 [==============================] - 0s 1ms/step - loss: 2.0378e-08 - accuracy: 1.0000
Epoch 95/100
12/12 [==============================] - 0s 1ms/step - loss: 1.8340e-08 - accuracy: 1.0000
Epoch 96/100
12/12 [==============================] - 0s 6ms/step - loss: 2.0378e-08 - accuracy: 1.0000
Epoch 97/100
12/12 [==============================] - 0s 1ms/step - loss: 2.0378e-08 - accuracy: 1.0000
Epoch 98/100
12/12 [==============================] - 0s 1ms/step - loss: 1.6302e-08 - accuracy: 1.0000
Epoch 99/100
12/12 [==============================] - 0s 7ms/step - loss: 1.4264e-08 - accuracy: 1.0000
Epoch 100/100
12/12 [==============================] - 0s 1ms/step - loss: 1.5283e-08 - accuracy: 1.0000
2/2 [==============================] - 0s 7ms/step
Epoch 1/100
12/12 [==============================] - 0s 3ms/step - loss: 2.3368 - accuracy: 0.1282
Epoch 2/100
12/12 [==============================] - 0s 1ms/step - loss: 1.6953 - accuracy: 0.6239
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 1.3144 - accuracy: 0.7863
Epoch 4/100
12/12 [==============================] - 0s 6ms/step - loss: 1.0299 - accuracy: 0.8462
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 0.8059 - accuracy: 0.9060
Epoch 6/100
12/12 [==============================] - 0s 6ms/step - loss: 0.6210 - accuracy: 0.9402
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4899 - accuracy: 0.9402
Epoch 8/100
12/12 [==============================] - 0s 7ms/step - loss: 0.3908 - accuracy: 0.9744
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 0.2994 - accuracy: 0.9915
Epoch 10/100

In [ ]:
print(best_params)

{'activation': 'relu', 'hidden_units': 64, 'optimizer': 'adam'}

## Hyperparameter tuning - Decision Tree

In [ ]:

dt_param_grid = {
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
dt_grid_search = GridSearchCV(dt, dt_param_grid, cv=5)
dt_grid_search.fit(X_train, y_train)
dt_best_params = dt_grid_search.best_params_

print("Best Hyperparameters for Decision Tree:")
for key, value in dt_best_params.items():
    print(key, ":", value)

best_dt_model = DecisionTreeClassifier(**dt_best_params)
joblib.dump(best_dt_model, '/work/models/best_dt_model.joblib')

Best Hyperparameters for Decision Tree:
max_depth : 30
min_samples_leaf : 1
min_samples_split : 5

['/work/models/best_dt_model.joblib']

In [ ]:
best_dt_model.fit(X_train,y_train)
accuracy = best_dt_model.score(X_test, y_test)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.6973684210526315

## Hyperparameter tuning - Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import joblib



# Define the grid search parameters
rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Perform GridSearchCV
rf_grid_search = GridSearchCV(rf, rf_param_grid, cv=5)
rf_grid_search.fit(X_train, y_train)

# Get the best hyperparameters
rf_best_params = rf_grid_search.best_params_

# Print the best hyperparameters
print("Best Hyperparameters for Random Forest:")
for key, value in rf_best_params.items():
    print(key, ":", value)

# Create a new random forest model with the best hyperparameters
best_rf_model = RandomForestClassifier(**rf_best_params)

# Train the best model on the entire training dataset
best_rf_model.fit(X_train, y_train)  # Fit the model

# Save the best model
joblib.dump(best_rf_model, '/work/models/best_rf_model.joblib')

# Evaluate the best model on the test data
accuracy = best_rf_model.score(X_test, y_test)
print("Test Accuracy:", accuracy)

Best Hyperparameters for Random Forest:
max_depth : 10
min_samples_leaf : 1
min_samples_split : 10
n_estimators : 300
Test Accuracy: 0.9078947368421053

## Hyperparameter tuning - XG Boost

In [ ]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import joblib


# Define the XGBoost classifier
xgb = XGBClassifier()

# Define the grid search parameters
xgb_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.3],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
}

# Perform GridSearchCV
xgb_grid_search = GridSearchCV(xgb, xgb_param_grid, cv=5)
xgb_grid_search.fit(X_train, y_train)

# Get the best hyperparameters
xgb_best_params = xgb_grid_search.best_params_

# Print the best hyperparameters
print("Best Hyperparameters for XGBoost:")
for key, value in xgb_best_params.items():
    print(key, ":", value)

# Create a new XGBoost model with the best hyperparameters
best_xgb_model = XGBClassifier(**xgb_best_params)

# Train the best model on the entire training dataset
best_xgb_model.fit(X_train, y_train)  # Fit the model

# Save the best model
joblib.dump(best_xgb_model, '/work/models/best_xgb_model.joblib')

# Evaluate the best model on the test data
accuracy = best_xgb_model.score(X_test, y_test)
print("Test Accuracy:", accuracy)

Best Hyperparameters for XGBoost:
colsample_bytree : 0.8
learning_rate : 0.3
max_depth : 3
n_estimators : 200
subsample : 0.8
Test Accuracy: 0.9210526315789473

## Hyperparameter tuning - KNN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
best_accuracy = 0
best_k = 0
for k in range(1, 21):  # testing from 1 to 20 neighbors
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_k = k

print(f"Best K: {best_k} with Accuracy: {best_accuracy}")


joblib.dump( knn,'/work/models/best_knn_model.joblib')

Best K: 5 with Accuracy: 0.6973684210526315

['/work/models/best_knn_model.joblib']

## Working with LazyClassifier

In [ ]:
!pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.2.12-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: click in /shared-libs/python3.9/py/lib/python3.9/site-packages (from lazypredict) (8.1.3)
Requirement already satisfied: pandas in /shared-libs/python3.9/py/lib/python3.9/site-packages (from lazypredict) (2.1.4)
Requirement already satisfied: tqdm in /shared-libs/python3.9/py/lib/python3.9/site-packages (from lazypredict) (4.64.1)
Requirement already satisfied: joblib in /shared-libs/python3.9/py/lib/python3.9/site-packages (from lazypredict) (1.2.0)
Requirement already satisfied: xgboost in /root/venv/lib/python3.9/site-packages (from lazypredict) (2.0.3)
Collecting lightgbm
  Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 113.1 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn in /shared-libs/python3.9/py/lib/python3.9/site-packages (from lazypredict) (1.1.2)
Requirement already satisfied: numpy in /shared-libs/python3.9/py/lib/python3.9/site-packages (from lightgbm->lazypredict) (1.23.4)
Requirement already satisfied: scipy in /shared-libs/python3.9/py/lib/python3.9/site-packages (from lightgbm->lazypredict) (1.9.3)
Requirement already satisfied: pytz>=2020.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from pandas->lazypredict) (2022.5)
Requirement already satisfied: tzdata>=2022.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from pandas->lazypredict) (2022.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from pandas->lazypredict) (2.8.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from scikit-learn->lazypredict) (3.1.0)
Requirement already satisfied: six>=1.5 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->lazypredict) (1.16.0)
Installing collected packages: lightgbm, lazypredict
Successfully installed lazypredict-0.2.12 lightgbm-4.3.0

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

In [ ]:
# Importing the data 
import pandas as pd
train=pd.read_csv('./Downloaded/vbd-richard-bernat/trainn.csv')
train.head()
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 65 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sudden_fever           252 non-null    int64
 1   headache               252 non-null    int64
 2   mouth_bleed            252 non-null    int64
 3   nose_bleed             252 non-null    int64
 4   muscle_pain            252 non-null    int64
 5   joint_pain             252 non-null    int64
 6   vomiting               252 non-null    int64
 7   rash                   252 non-null    int64
 8   diarrhea               252 non-null    int64
 9   hypotension            252 non-null    int64
 10  pleural_effusion       252 non-null    int64
 11  ascites                252 non-null    int64
 12  gastro_bleeding        252 non-null    int64
 13  swelling               252 non-null    int64
 14  nausea                 252 non-null    int64
 15  chills                 252 non-null    int64
 16  myalgia                252 non-null    int64
 17  digestion_trouble      252 non-null    int64
 18  fatigue                252 non-null    int64
 19  skin_lesions           252 non-null    int64
 20  stomach_pain           252 non-null    int64
 21  orbital_pain           252 non-null    int64
 22  neck_pain              252 non-null    int64
 23  weakness               252 non-null    int64
 24  back_pain              252 non-null    int64
 25  weight_loss            252 non-null    int64
 26  gum_bleed              252 non-null    int64
 27  jaundice               252 non-null    int64
 28  coma                   252 non-null    int64
 29  diziness               252 non-null    int64
 30  inflammation           252 non-null    int64
 31  red_eyes               252 non-null    int64
 32  loss_of_appetite       252 non-null    int64
 33  urination_loss         252 non-null    int64
 34  slow_heart_rate        252 non-null    int64
 35  abdominal_pain         252 non-null    int64
 36  light_sensitivity      252 non-null    int64
 37  yellow_skin            252 non-null    int64
 38  yellow_eyes            252 non-null    int64
 39  facial_distortion      252 non-null    int64
 40  microcephaly           252 non-null    int64
 41  rigor                  252 non-null    int64
 42  bitter_tongue          252 non-null    int64
 43  convulsion             252 non-null    int64
 44  anemia                 252 non-null    int64
 45  cocacola_urine         252 non-null    int64
 46  hypoglycemia           252 non-null    int64
 47  prostraction           252 non-null    int64
 48  hyperpyrexia           252 non-null    int64
 49  stiff_neck             252 non-null    int64
 50  irritability           252 non-null    int64
 51  confusion              252 non-null    int64
 52  tremor                 252 non-null    int64
 53  paralysis              252 non-null    int64
 54  lymph_swells           252 non-null    int64
 55  breathing_restriction  252 non-null    int64
 56  toe_inflammation       252 non-null    int64
 57  finger_inflammation    252 non-null    int64
 58  lips_irritation        252 non-null    int64
 59  itchiness              252 non-null    int64
 60  ulcers                 252 non-null    int64
 61  toenail_loss           252 non-null    int64
 62  speech_problem         252 non-null    int64
 63  bullseye_rash          252 non-null    int64
 64  prognosis              252 non-null    object
dtypes: int64(64), object(1)
memory usage: 128.1+ KB

In [ ]:
test=pd.read_csv('./Downloaded/vbd-richard-bernat/testt.csv')
test.head()
# Encoding the target variable
# label_encoder = LabelEncoder()
# train['prognosis_encoded'] = label_encoder.fit_transform(train['prognosis'])

,sudden_fever,headache,mouth_bleed,nose_bleed,muscle_pain,joint_pain,vomiting,rash,diarrhea,hypotension,...,breathing_restriction,toe_inflammation,finger_inflammation,lips_irritation,itchiness,ulcers,toenail_loss,speech_problem,bullseye_rash,prognosis
0,1,0,0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,Chikungunya
1,1,0,0,0,1,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,Dengue
2,1,1,1,1,0,1,0,1,0,1,...,0,1,0,1,0,0,0,0,0,Rift Valley fever
3,1,1,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Yellow Fever
4,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Zika

In [ ]:
train.info(),test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 65 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sudden_fever           252 non-null    int64
 1   headache               252 non-null    int64
 2   mouth_bleed            252 non-null    int64
 3   nose_bleed             252 non-null    int64
 4   muscle_pain            252 non-null    int64
 5   joint_pain             252 non-null    int64
 6   vomiting               252 non-null    int64
 7   rash                   252 non-null    int64
 8   diarrhea               252 non-null    int64
 9   hypotension            252 non-null    int64
 10  pleural_effusion       252 non-null    int64
 11  ascites                252 non-null    int64
 12  gastro_bleeding        252 non-null    int64
 13  swelling               252 non-null    int64
 14  nausea                 252 non-null    int64
 15  chills                 252 non-null    int64
 16  myalgia                252 non-null    int64
 17  digestion_trouble      252 non-null    int64
 18  fatigue                252 non-null    int64
 19  skin_lesions           252 non-null    int64
 20  stomach_pain           252 non-null    int64
 21  orbital_pain           252 non-null    int64
 22  neck_pain              252 non-null    int64
 23  weakness               252 non-null    int64
 24  back_pain              252 non-null    int64
 25  weight_loss            252 non-null    int64
 26  gum_bleed              252 non-null    int64
 27  jaundice               252 non-null    int64
 28  coma                   252 non-null    int64
 29  diziness               252 non-null    int64
 30  inflammation           252 non-null    int64
 31  red_eyes               252 non-null    int64
 32  loss_of_appetite       252 non-null    int64
 33  urination_loss         252 non-null    int64
 34  slow_heart_rate        252 non-null    int64
 35  abdominal_pain         252 non-null    int64
 36  light_sensitivity      252 non-null    int64
 37  yellow_skin            252 non-null    int64
 38  yellow_eyes            252 non-null    int64
 39  facial_distortion      252 non-null    int64
 40  microcephaly           252 non-null    int64
 41  rigor                  252 non-null    int64
 42  bitter_tongue          252 non-null    int64
 43  convulsion             252 non-null    int64
 44  anemia                 252 non-null    int64
 45  cocacola_urine         252 non-null    int64
 46  hypoglycemia           252 non-null    int64
 47  prostraction           252 non-null    int64
 48  hyperpyrexia           252 non-null    int64
 49  stiff_neck             252 non-null    int64
 50  irritability           252 non-null    int64
 51  confusion              252 non-null    int64
 52  tremor                 252 non-null    int64
 53  paralysis              252 non-null    int64
 54  lymph_swells           252 non-null    int64
 55  breathing_restriction  252 non-null    int64
 56  toe_inflammation       252 non-null    int64
 57  finger_inflammation    252 non-null    int64
 58  lips_irritation        252 non-null    int64
 59  itchiness              252 non-null    int64
 60  ulcers                 252 non-null    int64
 61  toenail_loss           252 non-null    int64
 62  speech_problem         252 non-null    int64
 63  bullseye_rash          252 non-null    int64
 64  prognosis              252 non-null    object
dtypes: int64(64), object(1)
memory usage: 128.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 65 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sudden_fever           11 non-null     int64
 1   headache               11 non-null     int64
 2   mouth_bleed            11 non-null     int64
 3   nose_bleed             11 non-null     int64
 4   muscle_pain            11 non-null     int64
 5   joint_pain             11 non-null     int64
 6   vomiting               11 non-null     int64
 7   rash                   11 non-null     int64
 8   diarrhea               11 non-null     int64
 9   hypotension            11 non-null     int64
 10  pleural_effusion       11 non-null     int64
 11  ascites                11 non-null     int64
 12  gastro_bleeding        11 non-null     int64
 13  swelling               11 non-null     int64
 14  nausea                 11 non-null     int64
 15  chills                 11 non-null     int64
 16  myalgia                11 non-null     int64
 17  digestion_trouble      11 non-null     int64
 18  fatigue                11 non-null     int64
 19  skin_lesions           11 non-null     int64
 20  stomach_pain           11 non-null     int64
 21  orbital_pain           11 non-null     int64
 22  neck_pain              11 non-null     int64
 23  weakness               11 non-null     int64
 24  back_pain              11 non-null     int64
 25  weight_loss            11 non-null     int64
 26  gum_bleed              11 non-null     int64
 27  jaundice               11 non-null     int64
 28  coma                   11 non-null     int64
 29  diziness               11 non-null     int64
 30  inflammation           11 non-null     int64
 31  red_eyes               11 non-null     int64
 32  loss_of_appetite       11 non-null     int64
 33  urination_loss         11 non-null     int64
 34  slow_heart_rate        11 non-null     int64
 35  abdominal_pain         11 non-null     int64
 36  light_sensitivity      11 non-null     int64
 37  yellow_skin            11 non-null     int64
 38  yellow_eyes            11 non-null     int64
 39  facial_distortion      11 non-null     int64
 40  microcephaly           11 non-null     int64
 41  rigor                  11 non-null     int64
 42  bitter_tongue          11 non-null     int64
 43  convulsion             11 non-null     int64
 44  anemia                 11 non-null     int64
 45  cocacola_urine         11 non-null     int64
 46  hypoglycemia           11 non-null     int64
 47  prostraction           11 non-null     int64
 48  hyperpyrexia           11 non-null     int64
 49  stiff_neck             11 non-null     int64
 50  irritability           11 non-null     int64
 51  confusion              11 non-null     int64
 52  tremor                 11 non-null     int64
 53  paralysis              11 non-null     int64
 54  lymph_swells           11 non-null     int64
 55  breathing_restriction  11 non-null     int64
 56  toe_inflammation       11 non-null     int64
 57  finger_inflammation    11 non-null     int64
 58  lips_irritation        11 non-null     int64
 59  itchiness              11 non-null     int64
 60  ulcers                 11 non-null     int64
 61  toenail_loss           11 non-null     int64
 62  speech_problem         11 non-null     int64
 63  bullseye_rash          11 non-null     int64
 64  prognosis              11 non-null     object
dtypes: int64(64), object(1)
memory usage: 5.7+ KB

(None, None)

In [ ]:
X,y = train.drop(['prognosis'],axis=1), train.prognosis
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [ ]:
from lazypredict.Supervised import LazyClassifier
clf = LazyClassifier(verbose=0,predictions=True)
models,predictions = clf.fit(X_train,X_test,y_train,y_test)
models

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
NuSVC,0.92,0.92,None,0.92,0.02
BernoulliNB,0.91,0.91,None,0.91,0.01
NearestCentroid,0.91,0.91,None,0.91,0.02
ExtraTreesClassifier,0.91,0.91,None,0.91,0.13
SVC,0.91,0.91,None,0.91,0.02
LogisticRegression,0.88,0.89,None,0.88,0.03
RandomForestClassifier,0.88,0.88,None,0.88,0.12
LinearDiscriminantAnalysis,0.87,0.87,None,0.86,0.09
SGDClassifier,0.86,0.87,None,0.85,0.07
LGBMClassifier,0.84,0.85,None,0.84,0.21
RidgeClassifierCV,0.84,0.84,None,0.82,0.12
RidgeClassifier,0.84,0.84,None,0.82,0.03
LinearSVC,0.83,0.84,None,0.82,0.14
PassiveAggressiveClassifier,0.82,0.83,None,0.81,0.02
CalibratedClassifierCV,0.82,0.82,None,0.80,0.19
BaggingClassifier,0.78,0.77,None,0.76,0.03
GaussianNB,0.75,0.76,None,0.73,0.02
Perceptron,0.74,0.75,None,0.71,0.01
DecisionTreeClassifier,0.75,0.75,None,0.73,0.01
KNeighborsClassifier,0.70,0.72,None,0.66,0.17
ExtraTreeClassifier,0.64,0.63,None,0.64,0.01
AdaBoostClassifier,0.14,0.19,None,0.09,0.08
QuadraticDiscriminantAnalysis,0.14,0.14,None,0.13,0.01
LabelSpreading,0.13,0.10,None,0.05,0.08
LabelPropagation,0.13,0.10,None,0.05,0.05
DummyClassifier,0.04,0.09,None,0.00,0.01

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=82fc1969-7ff0-4344-a3e7-65ed95a291e5' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>